### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by joshua840** [joshua840/ConceptualSensitivityRegularization#1]
## To-do lists
- [x] SmoothAttributionPrior -> CSR
  - Test list
  - [x] Catdog ERM / CSR
  - [x] Clear unnecessary file and function
  - [x] waterbirds_dataset.py vs waterbirds.py?
- [x] Modifying Concept dataset
  - [x] Extract a list of bgs and save it 
  - [x] Modify `Concept` dataset class
  - [x] Check whether it is well implemented or not
- [x] CatDog ver4
  - [x] Create a ipynb file that deals with crop and resize & metadata df 
  - [x] Check whether `CatDogVer4` dataset is well implemented by loading and plotting dataset via ipynb

## Workflow
- Create a new branch based on this issue (use vscode github extention)
- Continuously commit work done in the branch
- When doing pull-request, use git-rebase. It will help you follow the logs based on the name of issues

**Comment by joshua840** [comment]
potential issue can exist in the `set_minor_ratio` and `_remove_label_bias`, defined in `catdog_dataset.py`

**Comment by joshua840** [comment]
- Training time debugging
    
    `Trainer.fit`
    
    - `Trainer._fit_impl`
    - `Trainer._run`
    - `Trainer._run_stage`
    - `Trainer.fit_loop.run`
        - initialized during Trainer.__init__()
        
        ```python
        # FitLoop
        for epoch in range(max_epochs):
            # TrainingEpochLoop
            for batch_idx, batch in enumerate(train_dataloader):
                loss = lightning_module.training_step(batch, batch_idx)
                ...
        
                # ValidationEpochLoop
                for batch_idx, batch in enumerate(val_dataloader):
                    lightning_module.validation_step(batch, batch_idx)
                    ...
                ...
            ...
        ```
        
        - `_FitLoop.run`
            - While not self.done: ← iter over epoch is controlled here
            - _FitLoop.on_advanced_start()
            - _FitLoop.advance() ← takes long
            - _FitLoop.on_advanced_end()
        - `_FitLoop.advance`
            - `_TrainingEpochLoop.epoch_loop.run`
                - `_TrainingEpochLoop.reset` ← 0.0001sec
                - `_TrainingEpochLoop.on_run_start` ← 4sec
                - `_TrainingEpochLoop.advance()` ← fetch data from dataloader and update

- `_TrainingEpochLoop.on_run_start`
    - `iter(data_fetcher)` ← takes 4 sec
    - ##어떤 fetcher 쓰는지 알아내야함
    - 지금은 _DataFetcher 클래스 상속받는애들이 여럿 있음.
    - `_DataLoaderIterDataFetcher` ←
        - `self.iterator = iter(self.combined_loader)`
            - `iter(self.combined_loader)` is super slow!
            
            ```python
            class _DataFetcher(Iterator):
                def __iter__(self) -> "_DataFetcher":
                    self.reset()
                    self.iterator = iter(self.combined_loader)
            ```
            
            combinedLoader는 tr val te data loader중 하나이고 길이는 batch_size에 의해 달라짐

**Comment by joshua840** [comment]
combinedLoader를 따로  ipynb에서 불러와서 iter 씌우면 느려도 0.5초 안에 처리되는 걸 확인할 수 있음.
